title: L'oie Sauvage
email:
description: >- # this means to ignore newlines until "baseurl:"
  Hello, this is Yigit 🖖

  I'm a backend developer who's always looking to learn and improve.
baseurl: ""
url: ""
github_username: yigitsadic

theme: minima
minima:
  skin: dark

header_pages:
  - about.markdown
  - tags.markdown

defaults:
  - values:
      author: Yigit Sadic
